-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."TeamMember"
(
    "RollNumber" character varying,
    "Name" character varying,
    "Phone" integer,
    "Cgpa" double precision,
    "TeamId" character varying,
    "Position" character varying,
    PRIMARY KEY ("RollNumber", "TeamId")
);

CREATE TABLE IF NOT EXISTS public."Team"
(
    "TeamId" character varying,
    "SocietyId" character varying,
    "TeamName" character varying,
    PRIMARY KEY ("TeamId")
);

CREATE TABLE IF NOT EXISTS public."Society"
(
    "SocietyId" character varying,
    "SocietyName" character varying,
    PRIMARY KEY ("SocietyId")
);

CREATE TABLE IF NOT EXISTS public."Event"
(
    "EventId" character varying,
    "EventName" character varying,
    "SocietyId" character varying,
    PRIMARY KEY ("EventId")
);

CREATE TABLE IF NOT EXISTS public."Competition"
(
    "CompetitionId" character varying,
    "EventId" character varying,
    "CompetitionName" character varying,
    PRIMARY KEY ("CompetitionId")
);

CREATE TABLE IF NOT EXISTS public."CompetitionParticipant"
(
    "ParticipantId" character varying,
    "CompetitionId" character varying,
    "ParticipantName" character varying,
    "ParticipantPhone" integer,
    PRIMARY KEY ("ParticipantId", "CompetitionId")
);

CREATE TABLE IF NOT EXISTS public."EventParticipant"
(
    "P_Id" character varying,
    "EventId" character varying,
    "ParticipantName" character varying,
    "Participation Fee" integer,
    "EventDate" date,
    "ParticipantPhone" integer,
    PRIMARY KEY ("P_Id")
);

CREATE TABLE IF NOT EXISTS public."TeamMember_Team"
(
    "TeamMember_RollNumber" character varying,
    "Team_TeamId" character varying
);

CREATE TABLE IF NOT EXISTS public."CompetitionParticipant_competition"
(
    "CompetitionParticipant_ParticipantId" character varying,
    "competition_CompetitionId" character varying
);

CREATE TABLE IF NOT EXISTS public."Event_EventParticipant"
(
    "Event_EventId" character varying,
    "EventParticipant_P_Id" character varying
);

ALTER TABLE IF EXISTS public."Team"
    ADD FOREIGN KEY ("SocietyId")
    REFERENCES public."Society" ("SocietyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Event"
    ADD FOREIGN KEY ("SocietyId")
    REFERENCES public."Society" ("SocietyId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Competition"
    ADD FOREIGN KEY ("EventId")
    REFERENCES public."Event" ("EventId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TeamMember_Team"
    ADD FOREIGN KEY ("TeamMember_RollNumber")
    REFERENCES public."TeamMember" ("RollNumber") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TeamMember_Team"
    ADD FOREIGN KEY ("Team_TeamId")
    REFERENCES public."Team" ("TeamId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CompetitionParticipant_competition"
    ADD FOREIGN KEY ("CompetitionParticipant_ParticipantId")
    REFERENCES public."CompetitionParticipant" ("ParticipantId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CompetitionParticipant_competition"
    ADD FOREIGN KEY ("competition_CompetitionId")
    REFERENCES public."Competition" ("CompetitionId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Event_EventParticipant"
    ADD FOREIGN KEY ("Event_EventId")
    REFERENCES public."Event" ("EventId") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Event_EventParticipant"
    ADD FOREIGN KEY ("EventParticipant_P_Id")
    REFERENCES public."EventParticipant" ("P_Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;